// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7iST1GVY7MEDdpjnrPuCNJ
// Component: 0g0VB3cSY0U
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: hpLAsCB6dkK5a/component

import { useScreenVariants as useScreenVariantshT8MqvJo0QuvrA } from "./PlasmicGlobalVariant__Desktop"; // plasmic-import: hT8MQVJo0quvrA/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_cloud_wealth.module.css"; // plasmic-import: 7iST1GVY7MEDdpjnrPuCNJ/projectcss
import sty from "./PlasmicFooterDesktop.module.css"; // plasmic-import: 0g0VB3cSY0U/css

import DawnCheckMarksvg2Icon from "./icons/PlasmicIcon__DawnCheckMarksvg2"; // plasmic-import: uN0eLzMl3/icon
import LightBlueCheckMarksvgIcon from "./icons/PlasmicIcon__LightBlueCheckMarksvg"; // plasmic-import: ihRk4S87I/icon
import PotatoCheckMarksvgIcon from "./icons/PlasmicIcon__PotatoCheckMarksvg"; // plasmic-import: wtfIcxMRm/icon
import GreyCheckMarksvgIcon from "./icons/PlasmicIcon__GreyCheckMarksvg"; // plasmic-import: A_2frXz1p/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: LSNuBBNZXUjC6e/icon
import BlueArrowWhiteBackgroundBlueBordersvgIcon from "./icons/PlasmicIcon__BlueArrowWhiteBackgroundBlueBordersvg"; // plasmic-import: kgYwOcJGat/icon
import Group9Icon from "./icons/PlasmicIcon__Group9"; // plasmic-import: O_IQvBk0Ex/icon
import Line5Icon from "./icons/PlasmicIcon__Line5"; // plasmic-import: Ig28sg-IsK/icon

export type PlasmicFooterDesktop__VariantMembers = {};
export type PlasmicFooterDesktop__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooterDesktop__VariantsArgs;
export const PlasmicFooterDesktop__VariantProps = new Array<VariantPropType>();

export type PlasmicFooterDesktop__ArgsType = {};
type ArgPropType = keyof PlasmicFooterDesktop__ArgsType;
export const PlasmicFooterDesktop__ArgProps = new Array<ArgPropType>();

export type PlasmicFooterDesktop__OverridesType = {
  root?: p.Flex<"div">;
  yourPersonalVirtualFamilyOffice?: p.Flex<"div">;
  futureProof2?: p.Flex<"div">;
  pill3?: p.Flex<"div">;
  couple1?: p.Flex<"div">;
  keyFeaturesContainer?: p.Flex<"div">;
  futureProof?: p.Flex<"div">;
  pill2?: p.Flex<"div">;
  businessman1?: p.Flex<"div">;
  scalableMetrics?: p.Flex<"div">;
  button?: p.Flex<typeof Button>;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  globallyIncubateStandardsCompliantChannelsBeforeScalableBenefitsQuicklyDisseminateSuperiorDeliverablesWhereasWebEnabledApplicationsQuicklyDriveClicksAndMortarCatalystsForChangeBeforeVerticalArchitecturesCrediblyReintermediateBackendIdeasForCrossPlatformModelsContinuallyReintermediateIntegratedProcessesThroughTechnicallySoundIntellectualCapital?: p.Flex<"div">;
};

export interface DefaultFooterDesktopProps {
  className?: string;
}

function PlasmicFooterDesktop__RenderFunc(props: {
  variants: PlasmicFooterDesktop__VariantsArgs;
  args: PlasmicFooterDesktop__ArgsType;
  overrides: PlasmicFooterDesktop__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    desktop: useScreenVariantshT8MqvJo0QuvrA()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"yourPersonalVirtualFamilyOffice"}
        data-plasmic-override={overrides.yourPersonalVirtualFamilyOffice}
        className={classNames(
          projectcss.all,
          sty.yourPersonalVirtualFamilyOffice
        )}
      >
        <p.Stack
          as={"div"}
          data-plasmic-name={"futureProof2"}
          data-plasmic-override={overrides.futureProof2}
          hasGap={true}
          className={classNames(projectcss.all, sty.futureProof2)}
        >
          <div
            data-plasmic-name={"pill3"}
            data-plasmic-override={overrides.pill3}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.pill3
            )}
          >
            {"future-proof"}
          </div>
        </p.Stack>

        <h2
          className={classNames(
            projectcss.all,
            projectcss.h2,
            projectcss.__wab_text,
            sty.h2__gK9S
          )}
        >
          {"Your Personal Virtual Family Office"}
        </h2>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__osMTx
          )}
        >
          {
            "All fiduciary, financial, legal and KYC tools, knowledge base and documentation accessible from a single app 24/7/365."
          }
        </div>

        <div className={classNames(projectcss.all, sty.freeBox__vlj7T)}>
          <div className={classNames(projectcss.all, sty.freeBox__dAgQ)}>
            <div className={classNames(projectcss.all, sty.freeBox___6G2Me)}>
              <DawnCheckMarksvg2Icon
                className={classNames(projectcss.all, sty.svg__tEsjn)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xbxzh
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__xpWrk
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5___6DSg6
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#0F5CBF" }}
                              >
                                {
                                  "Access and Distribute Documents Safely and Securely"
                                }
                              </span>
                            </React.Fragment>
                          </h5>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h3>
                  }
                  <React.Fragment>
                    {
                      "With our secure File Vault, your advisor can safely store information they wish to share with you on your password-protected files without the need traditional methods"
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__vt21M)}>
              <LightBlueCheckMarksvgIcon
                className={classNames(projectcss.all, sty.svg__i8HHa)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fxHan
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__rvxT
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__qQ2Vd
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#0F5CBF" }}
                              >
                                {
                                  "Communicate Safely and Securely with Verified Advisors"
                                }
                              </span>
                            </React.Fragment>
                          </h5>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h3>
                  }
                  <React.Fragment>
                    {
                      "Privacy is non-negotiable when it comes to your finances. Having access to a secure chat facility, you can now interact with your advisor securely on the system, thereby eliminating the risk of sensitive information becoming vulnerable.."
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__xi2Wl)}>
              <PotatoCheckMarksvgIcon
                className={classNames(projectcss.all, sty.svg__gauLj)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2D6KR
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__bDzJy
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__tDpa8
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#0F5CBF" }}
                              >
                                {"Access to Industry Leading Tools"}
                              </span>
                            </React.Fragment>
                          </h5>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h3>
                  }
                  <React.Fragment>
                    {
                      "With our industry leading tools, you will be able to better manage your personal wealth virtually. Attend virtual meetings, sign resolutions digitally, manage your diary, record and automatically minute virtual meetings, make amendments to your will, do scenario planning or just see how much tax you'll most likely have to pay. The possibilities are many."
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__qOj1W)}>
              <GreyCheckMarksvgIcon
                className={classNames(projectcss.all, sty.svg__eb9Uu)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lwvNm
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__pdNu7
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__hU5Ou
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#0F5CBF" }}
                              >
                                {"Focus on Growth, Not Paperwork"}
                              </span>
                            </React.Fragment>
                          </h5>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h3>
                  }
                  <React.Fragment>
                    {
                      "Reduce the amount of paperwork you do by populating your details in your profile, and let our document automation do the rest. "
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"couple1"}
            data-plasmic-override={overrides.couple1}
            className={classNames(projectcss.all, sty.couple1)}
          />
        </div>
      </div>

      <div
        data-plasmic-name={"keyFeaturesContainer"}
        data-plasmic-override={overrides.keyFeaturesContainer}
        className={classNames(projectcss.all, sty.keyFeaturesContainer)}
      >
        <p.Stack
          as={"div"}
          data-plasmic-name={"futureProof"}
          data-plasmic-override={overrides.futureProof}
          hasGap={true}
          className={classNames(projectcss.all, sty.futureProof)}
        >
          <div
            data-plasmic-name={"pill2"}
            data-plasmic-override={overrides.pill2}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.pill2
            )}
          >
            {"future-proof"}
          </div>
        </p.Stack>

        <h2
          className={classNames(
            projectcss.all,
            projectcss.h2,
            projectcss.__wab_text,
            sty.h2__cuvd0
          )}
        >
          {
            "Results-focussed Client Management for Financial Planners and Fiduciary Practitioners"
          }
        </h2>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__aBjrr
          )}
        >
          {
            "All fiduciary, financial, legal and KYC tools, knowledge base and documentation accessible from a single app 24/7/365."
          }
        </div>

        {(
          hasVariant(globalVariants, "desktop", "mobileOnly") ? true : false
        ) ? (
          <div className={classNames(projectcss.all, sty.freeBox__pcBiE)}>
            <div className={classNames(projectcss.all, sty.freeBox___4JtoI)}>
              <DawnCheckMarksvg2Icon
                className={classNames(projectcss.all, sty.svg__cWktY)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1Ji6X
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__xa1Uo
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__mEBfr
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#0F5CBF" }}
                              >
                                {"Automated Customer KYC"}
                              </span>
                            </React.Fragment>
                          </h5>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h3>
                  }
                  <React.Fragment>
                    {
                      "Reduce onboarding turn-around with digitally pre-verified customers.   "
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox___0TzjC)}>
              <LightBlueCheckMarksvgIcon
                className={classNames(projectcss.all, sty.svg__pDm5K)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nzUdi
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__ffqsR
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__fHxNb
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#0F5CBF" }}
                              >
                                {"Bridge the Knowledge-Gap"}
                              </span>
                            </React.Fragment>
                          </h5>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h3>
                  }
                  <React.Fragment>
                    {
                      "Cross-functional, automated wizard generating up-to-date industry standard reports based on real-world scenarios and calculations."
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__yeWoi)}>
              <PotatoCheckMarksvgIcon
                className={classNames(projectcss.all, sty.svg__pyXpY)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gwdGu
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___5K9IJ
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__tTtSa
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#0F5CBF" }}
                              >
                                {"Scalable Client Management"}
                              </span>
                            </React.Fragment>
                          </h5>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h3>
                  }
                  <React.Fragment>
                    {
                      "Communicate, Manage KYC, Track, Record, Share Documents Instantly "
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__q4OwN)}>
              <GreyCheckMarksvgIcon
                className={classNames(projectcss.all, sty.svg__sLpSe)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__q6HbD
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__mF2Wa
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__qKlGt
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#0F5CBF" }}
                              >
                                {"Auto-Generated Documents"}
                              </span>
                            </React.Fragment>
                          </h5>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h3>
                  }
                  <React.Fragment>
                    {
                      "Generate Wills, Trust Deeds, Estate Plans, Financial Plans and Scenario Plans at the click of a button"
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___1P7G)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/cloud_wealth/images/businessman1Png.png",
                fullWidth: 499,
                fullHeight: 637,
                aspectRatio: undefined
              }}
            />
          </div>
        ) : null}
        {(hasVariant(globalVariants, "desktop", "mobileOnly") ? true : true) ? (
          <div className={classNames(projectcss.all, sty.freeBox__uma)}>
            <div
              data-plasmic-name={"businessman1"}
              data-plasmic-override={overrides.businessman1}
              className={classNames(projectcss.all, sty.businessman1)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__xPhxA)}>
              <div className={classNames(projectcss.all, sty.freeBox__nnAn)}>
                <DawnCheckMarksvg2Icon
                  className={classNames(projectcss.all, sty.svg__smKfZ)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hNkrj
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__nXHc
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <h5
                              className={classNames(
                                projectcss.all,
                                projectcss.h5,
                                projectcss.__wab_text,
                                sty.h5__toCfI
                              )}
                            >
                              <React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ color: "#0F5CBF" }}
                                >
                                  {"Automated Customer KYC"}
                                </span>
                              </React.Fragment>
                            </h5>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </h3>
                    }
                    <React.Fragment>
                      {
                        "Reduce onboarding turn-around with digitally pre-verified customers.   "
                      }
                    </React.Fragment>
                  </React.Fragment>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__k43U)}>
                <LightBlueCheckMarksvgIcon
                  className={classNames(projectcss.all, sty.svg__xT0M)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ueQjE
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__hzbvz
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <h5
                              className={classNames(
                                projectcss.all,
                                projectcss.h5,
                                projectcss.__wab_text,
                                sty.h5__dVoSi
                              )}
                            >
                              <React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ color: "#0F5CBF" }}
                                >
                                  {"Bridge the Knowledge-Gap"}
                                </span>
                              </React.Fragment>
                            </h5>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </h3>
                    }
                    <React.Fragment>
                      {
                        "Cross-functional, automated wizard generating up-to-date industry standard reports based on real-world scenarios and calculations."
                      }
                    </React.Fragment>
                  </React.Fragment>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__jr9NR)}>
                <PotatoCheckMarksvgIcon
                  className={classNames(projectcss.all, sty.svg___39RSz)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mwSd5
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__l5OsG
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <h5
                              className={classNames(
                                projectcss.all,
                                projectcss.h5,
                                projectcss.__wab_text,
                                sty.h5__yTou
                              )}
                            >
                              <React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ color: "#0F5CBF" }}
                                >
                                  {"Scalable Client Management"}
                                </span>
                              </React.Fragment>
                            </h5>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </h3>
                    }
                    <React.Fragment>
                      {
                        "Communicate, Manage KYC, Track, Record, Share Documents Instantly "
                      }
                    </React.Fragment>
                  </React.Fragment>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__cemjd)}>
                <GreyCheckMarksvgIcon
                  className={classNames(projectcss.all, sty.svg__iCyU7)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vzDvg
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__a9CSb
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <h5
                              className={classNames(
                                projectcss.all,
                                projectcss.h5,
                                projectcss.__wab_text,
                                sty.h5__nUyE5
                              )}
                            >
                              <React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ color: "#0F5CBF" }}
                                >
                                  {"Auto-Generated Documents"}
                                </span>
                              </React.Fragment>
                            </h5>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </h3>
                    }
                    <React.Fragment>
                      {
                        "Generate Wills, Trust Deeds, Estate Plans, Financial Plans and Scenario Plans at the click of a button"
                      }
                    </React.Fragment>
                  </React.Fragment>
                </div>
              </div>
            </div>
          </div>
        ) : null}
      </div>

      <div
        data-plasmic-name={"scalableMetrics"}
        data-plasmic-override={overrides.scalableMetrics}
        className={classNames(projectcss.all, sty.scalableMetrics)}
      >
        {(hasVariant(globalVariants, "desktop", "mobileOnly") ? true : true) ? (
          <h2
            className={classNames(
              projectcss.all,
              projectcss.h2,
              projectcss.__wab_text,
              sty.h2__fwNgS
            )}
          >
            <React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"Scalable Customer Growth:"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"A cloud-based paperless Tool"}
              </span>
            </React.Fragment>
          </h2>
        ) : null}
        {(hasVariant(globalVariants, "desktop", "mobileOnly") ? true : true) ? (
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___7UvWq
            )}
          >
            <React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Manage mutliple clients from one single platform. Built with financial planners, trustees and other fiduciary practitioners in mind, CloudWealth streamlines  day-to-day management of wealth structures, regulatory tasks, and seamlessly integrates communication with clients from a single interface."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"Work from anywhere has never been more accessible than now."}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "With our MFA(Multi-Factor Authentication), you can safely and securely manage your client base from anywhere in the world."
                }
              </span>
            </React.Fragment>
          </div>
        ) : null}

        <div className={classNames(projectcss.all, sty.freeBox__vGb54)}>
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__mvsil)}
            displayHeight={
              hasVariant(globalVariants, "desktop", "mobileOnly")
                ? ("338px" as const)
                : ("575px" as const)
            }
            displayMaxHeight={"none" as const}
            displayMaxWidth={"100%" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={
              hasVariant(globalVariants, "desktop", "mobileOnly")
                ? ("489px" as const)
                : ("536px" as const)
            }
            loading={"lazy" as const}
            src={{
              src: "/plasmic/cloud_wealth/images/womanWithLaptop1Png.png",
              fullWidth: 499,
              fullHeight: 506,
              aspectRatio: undefined
            }}
          />

          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__ouGb3)}>
              {(
                hasVariant(globalVariants, "desktop", "mobileOnly")
                  ? true
                  : true
              ) ? (
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___6CV4L
                  )}
                >
                  {"Results-focussed Client Management for Financial"}
                </h2>
              ) : null}
              {(
                hasVariant(globalVariants, "desktop", "mobileOnly")
                  ? true
                  : true
              ) ? (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vzwFf
                  )}
                >
                  {
                    "All fiduciary, financial, legal and KYC tools, knowledge base and documentation accessible from a single app 24/7/365. All fiduciary, financial, legal and KYC tools, knowledge base and documentation accessible from a single app 24/7/365.\n\nAll fiduciary, financial, legal and KYC tools, knowledge base and documentation accessible from a single app 24/7/365.All fiduciary, financial, legal and KYC tools, knowledge base and documentation accessible from a single app 24/7/365.\n\n"
                  }
                </div>
              ) : null}

              <Button
                data-plasmic-name={"button"}
                data-plasmic-override={overrides.button}
                className={classNames("__wab_instance", sty.button)}
                color={"red" as const}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bk3Ey
                  )}
                >
                  {"View Our Documentation"}
                </div>
              </Button>

              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__t5Ga)}>
                  <BlueArrowWhiteBackgroundBlueBordersvgIcon
                    className={classNames(projectcss.all, sty.svg___8I7Hc)}
                    role={"img"}
                  />

                  <p.PlasmicLink
                    data-plasmic-name={"link"}
                    data-plasmic-override={overrides.link}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Sign Up Now"}
                  </p.PlasmicLink>
                </div>
              ) : null}
            </div>
          ) : null}
        </div>
      </div>

      <div className={classNames(projectcss.all, sty.freeBox__c5Ryk)}>
        <Group9Icon
          className={classNames(projectcss.all, sty.svg__cpdhK)}
          role={"img"}
        />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__rM67
          )}
        >
          {"Home\n\nAbout\n\nCalculators\n\nFeatures\n\nPartners"}
        </div>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__kmSl
          )}
        >
          {
            "Estate Planning\n\nFinancial Planning\n\nFiduciary Services\n\nProducts\n\nResources"
          }
        </div>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___3BMiv
          )}
        >
          {
            "Our Technology\n\nDocumentation\n\nPresentations\n\nTutorials\n\nVersion History"
          }
        </div>

        <Line5Icon
          className={classNames(projectcss.all, sty.svg__nqyxU)}
          role={"img"}
        />
      </div>

      <div className={classNames(projectcss.all, sty.freeBox__oSnVm)}>
        {(hasVariant(globalVariants, "desktop", "mobileOnly") ? true : true) ? (
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__x7FwB
            )}
          >
            {
              "Privacy Policy            Terms & Conditions            Cookie Policy"
            }
          </div>
        ) : null}
      </div>

      {(hasVariant(globalVariants, "desktop", "mobileOnly") ? true : true) ? (
        <div
          data-plasmic-name={
            "globallyIncubateStandardsCompliantChannelsBeforeScalableBenefitsQuicklyDisseminateSuperiorDeliverablesWhereasWebEnabledApplicationsQuicklyDriveClicksAndMortarCatalystsForChangeBeforeVerticalArchitecturesCrediblyReintermediateBackendIdeasForCrossPlatformModelsContinuallyReintermediateIntegratedProcessesThroughTechnicallySoundIntellectualCapital"
          }
          data-plasmic-override={
            overrides.globallyIncubateStandardsCompliantChannelsBeforeScalableBenefitsQuicklyDisseminateSuperiorDeliverablesWhereasWebEnabledApplicationsQuicklyDriveClicksAndMortarCatalystsForChangeBeforeVerticalArchitecturesCrediblyReintermediateBackendIdeasForCrossPlatformModelsContinuallyReintermediateIntegratedProcessesThroughTechnicallySoundIntellectualCapital
          }
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.globallyIncubateStandardsCompliantChannelsBeforeScalableBenefitsQuicklyDisseminateSuperiorDeliverablesWhereasWebEnabledApplicationsQuicklyDriveClicksAndMortarCatalystsForChangeBeforeVerticalArchitecturesCrediblyReintermediateBackendIdeasForCrossPlatformModelsContinuallyReintermediateIntegratedProcessesThroughTechnicallySoundIntellectualCapital
          )}
        >
          {
            "Globally incubate standards compliant channels before scalable benefits. Quickly disseminate superior deliverables whereas web-enabled applications. Quickly drive clicks-and-mortar catalysts for change before vertical architectures. Credibly reintermediate backend ideas for cross-platform models. Continually reintermediate integrated processes through technically sound intellectual capital. "
          }
        </div>
      ) : null}
      {(hasVariant(globalVariants, "desktop", "mobileOnly") ? true : true) ? (
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__taO16
          )}
        >
          <React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ color: "#000000" }}
            >
              {"Privacy Policy-Terms & Conditions  Cookie Policy"}
            </span>
          </React.Fragment>
        </div>
      ) : null}
      {(hasVariant(globalVariants, "desktop", "mobileOnly") ? true : false) ? (
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__op5P6
          )}
        >
          {
            "Globally incubate standards compliant channels before scalable benefits. Quickly disseminate superior deliverables whereas web-enabled applications. Quickly drive clicks-and-mortar catalysts for change before vertical architectures. Credibly reintermediate backend ideas for cross-platform models. Continually reintermediate integrated processes through technically sound intellectual capital. "
          }
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "yourPersonalVirtualFamilyOffice",
    "futureProof2",
    "pill3",
    "couple1",
    "keyFeaturesContainer",
    "futureProof",
    "pill2",
    "businessman1",
    "scalableMetrics",
    "button",
    "link",
    "globallyIncubateStandardsCompliantChannelsBeforeScalableBenefitsQuicklyDisseminateSuperiorDeliverablesWhereasWebEnabledApplicationsQuicklyDriveClicksAndMortarCatalystsForChangeBeforeVerticalArchitecturesCrediblyReintermediateBackendIdeasForCrossPlatformModelsContinuallyReintermediateIntegratedProcessesThroughTechnicallySoundIntellectualCapital"
  ],
  yourPersonalVirtualFamilyOffice: [
    "yourPersonalVirtualFamilyOffice",
    "futureProof2",
    "pill3",
    "couple1"
  ],
  futureProof2: ["futureProof2", "pill3"],
  pill3: ["pill3"],
  couple1: ["couple1"],
  keyFeaturesContainer: [
    "keyFeaturesContainer",
    "futureProof",
    "pill2",
    "businessman1"
  ],
  futureProof: ["futureProof", "pill2"],
  pill2: ["pill2"],
  businessman1: ["businessman1"],
  scalableMetrics: ["scalableMetrics", "button", "link"],
  button: ["button"],
  link: ["link"],
  globallyIncubateStandardsCompliantChannelsBeforeScalableBenefitsQuicklyDisseminateSuperiorDeliverablesWhereasWebEnabledApplicationsQuicklyDriveClicksAndMortarCatalystsForChangeBeforeVerticalArchitecturesCrediblyReintermediateBackendIdeasForCrossPlatformModelsContinuallyReintermediateIntegratedProcessesThroughTechnicallySoundIntellectualCapital:
    [
      "globallyIncubateStandardsCompliantChannelsBeforeScalableBenefitsQuicklyDisseminateSuperiorDeliverablesWhereasWebEnabledApplicationsQuicklyDriveClicksAndMortarCatalystsForChangeBeforeVerticalArchitecturesCrediblyReintermediateBackendIdeasForCrossPlatformModelsContinuallyReintermediateIntegratedProcessesThroughTechnicallySoundIntellectualCapital"
    ]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  yourPersonalVirtualFamilyOffice: "div";
  futureProof2: "div";
  pill3: "div";
  couple1: "div";
  keyFeaturesContainer: "div";
  futureProof: "div";
  pill2: "div";
  businessman1: "div";
  scalableMetrics: "div";
  button: typeof Button;
  link: "a";
  globallyIncubateStandardsCompliantChannelsBeforeScalableBenefitsQuicklyDisseminateSuperiorDeliverablesWhereasWebEnabledApplicationsQuicklyDriveClicksAndMortarCatalystsForChangeBeforeVerticalArchitecturesCrediblyReintermediateBackendIdeasForCrossPlatformModelsContinuallyReintermediateIntegratedProcessesThroughTechnicallySoundIntellectualCapital: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooterDesktop__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooterDesktop__VariantsArgs;
    args?: PlasmicFooterDesktop__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFooterDesktop__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicFooterDesktop__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicFooterDesktop__ArgProps,
          internalVariantPropNames: PlasmicFooterDesktop__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicFooterDesktop__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooterDesktop";
  } else {
    func.displayName = `PlasmicFooterDesktop.${nodeName}`;
  }
  return func;
}

export const PlasmicFooterDesktop = Object.assign(
  // Top-level PlasmicFooterDesktop renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    yourPersonalVirtualFamilyOffice: makeNodeComponent(
      "yourPersonalVirtualFamilyOffice"
    ),
    futureProof2: makeNodeComponent("futureProof2"),
    pill3: makeNodeComponent("pill3"),
    couple1: makeNodeComponent("couple1"),
    keyFeaturesContainer: makeNodeComponent("keyFeaturesContainer"),
    futureProof: makeNodeComponent("futureProof"),
    pill2: makeNodeComponent("pill2"),
    businessman1: makeNodeComponent("businessman1"),
    scalableMetrics: makeNodeComponent("scalableMetrics"),
    button: makeNodeComponent("button"),
    link: makeNodeComponent("link"),
    globallyIncubateStandardsCompliantChannelsBeforeScalableBenefitsQuicklyDisseminateSuperiorDeliverablesWhereasWebEnabledApplicationsQuicklyDriveClicksAndMortarCatalystsForChangeBeforeVerticalArchitecturesCrediblyReintermediateBackendIdeasForCrossPlatformModelsContinuallyReintermediateIntegratedProcessesThroughTechnicallySoundIntellectualCapital:
      makeNodeComponent(
        "globallyIncubateStandardsCompliantChannelsBeforeScalableBenefitsQuicklyDisseminateSuperiorDeliverablesWhereasWebEnabledApplicationsQuicklyDriveClicksAndMortarCatalystsForChangeBeforeVerticalArchitecturesCrediblyReintermediateBackendIdeasForCrossPlatformModelsContinuallyReintermediateIntegratedProcessesThroughTechnicallySoundIntellectualCapital"
      ),

    // Metadata about props expected for PlasmicFooterDesktop
    internalVariantProps: PlasmicFooterDesktop__VariantProps,
    internalArgProps: PlasmicFooterDesktop__ArgProps
  }
);

export default PlasmicFooterDesktop;
/* prettier-ignore-end */
